@startuml
'https://plantuml.com/use-case-diagram


(StartGame)
(RegisterPlayers) as (UC2)
usecase ThrowAndMove
usecase LandAndAct
usecase endGame
usecase LandOnProperty
usecase moneyWithDrawl
usecase goToJail
usecase LandOnChance
usecase LandOnTax

player as actor
player --> (StartGame)
(StartGame) --> (RegisterPlayers)
(RegisterPlayers) --> (ThrowAndMove)
(ThrowAndMove) -> endGame
ThrowAndMove --> LandAndAct
endGame --> (RegisterPlayers)
LandAndAct --> ThrowAndMove
LandAndAct --> LandOnProperty
LandAndAct --> goToJail
LandAndAct --> LandOnChance
LandAndAct --> LandOnTax
LandOnProperty --> moneyWithDrawl
LandOnTax --> moneyWithDrawl
moneyWithDrawl --> endGame














@enduml