@startuml
actor user as uc
actor player as uc9

usecase "StartGame" as uc1
usecase "RegisterPlayers" as uc2
usecase "ThrowAndMove" as uc3
usecase "LandAndAct" as uc4
usecase "EndGame" as uc5


uc --> uc1
uc1 --> uc2
uc9 --> uc3
uc2 --> uc3
uc3 --> uc4
uc4 --> uc3
uc4 --> uc5

@enduml