@startuml
'https://plantuml.com/sequence-diagram


Main -> Game: startSession()



Game -> FileIO: String[] fielddata = readBoardData("fields.csv")
Game -> FileIO: String[] carddata = readBoardData("cards.csv")

Game -> Board : new(fielddata, (carddata))
Board -> Board : createFields(fielddata)

loop fielddata.length
Board -> Field : new (id, label, cost, income)
end

Board -> CardDeck : cardDeck = new(carddata)
CardDeck -> CardDeck : createCards(data)

loop data.length
CardDeck -> Card : new (message, income, cost, event)
end

Board -> Field : Chance.setCardDeck(cardDeck)


@enduml