@startuml

participant Main as main
participant Game as game
participant Dice as dice
participant Player as player
participant Board as board

game -> game : throwAndMove()

game -> TextUI : displayMessage ("Det er "+currentPlayer.getName+"'s tur")
game -> dice : int result = rollDiceSum()
dice --> game : 8
game -> ui : displayMessage(currentPlayer.getName+" slog "+ result )

game -> player: int newPosition = updatePosition( result )
player --> game : 9
game -> board : Field f = getField( newPosition )
board --> game : (Valbylanggade)
game -> game : landAndAct(f)

@enduml