@startuml
'https://plantuml.com/sequence-diagram


Game -> Game : Setup
Game -> FileIO : String[] fielddata = readBoardData("feilds.csv")
Game -> Board : new(fielddata)
Board -> Board : createFields(data)

loop data.length
Board -> Field : new (id,label,cost,income)
end

Game -> FileIO : String[] cardData = readBoardData("cards.csv")
Game -> CardDeck : new(cardData)
CardDeck -> CardDeck : createCards(data)

loop data.length
CardDeck -> Card : new(message, income, cost, event)
end

@enduml