@startuml
'https://plantuml.com/sequence-diagram

participant Game as game
participant TextUI as ui
participant Tax as subfield
participant Field  as field


game -> game : landAndAct(f)
game -> subfield : msg = onLand(player)
subfield -> field : msg = super.onLand(player);
field --> subfield : "Du er landet på skat."
subfield --> game:   "Du er landet på skat. Vil du betale fast beløb på "+this.cost+"kr? (Tast Y). Ellers trækker vi et beløb der svarer til 10 % af dine aktiver (Tast N)"

game -> ui : response = promptBinary( msg )

ui --> game : true
'game -> field : msg = processResponse(player, response)

alt response == true
     field -> subfield: onAccept()
     subField --> game: "Egon har betalt 10% i skat"
   else
     field -> subfield: onReject()
     subField --> game: "Egon har betalt 4000kr i skat"
end



game -> ui : displayMessage( msg )


@enduml
