@startuml
'https://plantuml.com/sequence-diagram
participant TextUI as ui
participant Game as game
participant Property  as subField
participant Field  as field

game -> ui:promptBinary("Egon er landet på Valbylanggade.\n Vil du købe? Y/N")
ui --> game: true

'game -> field : msg = processResponse(player, response )

alt response true
    game  -> subField : onAccept(player)

    alt option == "buy"
        subField  -> Player: buyProperty(this)
        Player -> Account : withdraw(costOfField)
        subField --> game : "Egon købte Valbylanggade"

    else option == "build"
             subField -> Player: buildHouse()
             Player -> Account : withdraw(houseCost)
              subField --> game : "Egon byggede på Valbylanggade"

    end

else response false
    game -> subField : onReject(player)
        alt option == "buy"
            subField --> game: "Egon afviste købstilbud."

        else option == "build"
              subField --> game: "Egon afviste at bygge"

        end

    end


game -> ui : displayMessage( msg )

@enduml