@startuml
'https://plantuml.com/sequence-diagram
participant TextUI as ui
participant Game as game

participant Tax as subfield
participant Field  as field


game -> game : landAndAct(f)
game -> subfield : msg = onLand(player)
subfield -> field : msg = super.onLand(player);
field --> subfield : "Du er landet på skat."
subfield -> subfield : msg+="Du skal betale et beløb der svarer til 10 % af dine aktiver.\nVil du hellere betale et fast beløb på 4000kr?(Y/N)"
subfield --> game:   "Du er landet på skat. Du skal betale et beløb der svarer til 10 % af dine aktiver.\n Vil du hellere betale et fast beløb på 4000kr?(Y/N)"

game -> ui : response = promptBinary( msg )

ui --> game : true
'game -> field : msg = processResponse(player, response)

alt response == true
     game -> subfield: onAccept()
     subfield --> game: "Egon har betalt 10% i skat"
   else
     game -> subfield: onReject()
     subfield --> game: "Egon har betalt 4000kr i skat"
end



game -> ui : displayMessage( msg )


@enduml
