@startuml

'Use-case by CPHJL325 // Jonas Meinert Larsen

'Player

 actor user as u

'Use-cases from our ../wiki text

 usecase "StartGame" as sg
 usecase "RegisterPlayers" as rp
 usecase "ThrowAndMove" as tam
 usecase "LandAndAct" as laa
 usecase "EndGame" as eg
 usecase "WithdrawMoney" as wm
 usecase "LandOnProperty" as lop
 usecase "LandOnChance" as loc
 usecase "LandOnTax" as lot

'Display

u --> sg
sg --> rp
rp --> tam
tam --> laa
laa --> lop
laa --> loc
laa --> lot
lop --> wm
laa --> tam
loc --> wm
lot --> wm
tam --> eg
wm --> eg

'Notes

note as n1
    <b>Use-case diagram by CPHJL325</b>
    <b>Version 1.0</b>
    <b>Date: <color :blue>25/03-2025</color></b>
end note

@enduml